"use client";

import Link from "next/link";
import { Trash2, X, ArrowRight, ShoppingBag } from "lucide-react";
import { useCartStore } from "@/lib/store";
import { formatCurrency } from "@/lib/utils";

interface CartDrawerProps { isOpen: boolean; onClose: () => void; }

export function CartDrawer({ isOpen, onClose }: CartDrawerProps) {
  const { items, removeItem } = useCartStore();
  const total = items.reduce((sum, item) => sum + item.price * (item.quantity || 1), 0);
  return <><div className={`fixed inset-0 z-50 bg-ink/40 backdrop-blur-sm transition-opacity ${isOpen?"opacity-100":"pointer-events-none opacity-0"}`} onClick={onClose}/><aside className={`fixed right-0 top-0 z-[60] flex h-full w-full max-w-[420px] flex-col border-l border-ink/10 bg-card shadow-2xl transition-transform duration-300 ${isOpen?"translate-x-0":"translate-x-full"}`} aria-hidden={!isOpen}><div className="flex items-center justify-between border-b border-ink/10 p-6"><div><span className="font-tag text-[9px] uppercase tracking-[.18em] text-poppy">NovaCart</span><h2 className="font-display italic text-2xl text-ink">Your bag.</h2></div><button onClick={onClose} aria-label="Close bag" className="rounded-full p-2 text-ink-soft hover:bg-cream hover:text-ink"><X className="h-5 w-5"/></button></div><div className="flex-1 overflow-y-auto p-6">{items.length===0?<div className="flex h-full flex-col items-center justify-center text-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-cream text-ink-soft"><ShoppingBag className="h-6 w-6"/></div><p className="mt-4 text-sm font-semibold text-ink">Your bag is empty.</p><p className="mt-1 text-xs text-ink-soft">Add something lovely and come back here.</p></div>:<div className="space-y-5">{items.map(item=><div key={item.id} className="flex gap-4"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-cream"><img src={item.imageUrl} alt={item.title} className="h-full w-full object-cover"/></div><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold text-ink">{item.title}</h3><p className="mt-1 text-xs text-ink-soft">Qty: {item.quantity||1}</p><div className="mt-3 flex items-center justify-between"><span className="font-tag text-sm font-bold text-poppy">{formatCurrency(item.price*(item.quantity||1))}</span><button onClick={()=>removeItem(item.id)} aria-label={`Remove ${item.title}`} className="text-ink-soft hover:text-poppy"><Trash2 className="h-4 w-4"/></button></div></div></div>)}</div>}</div>{items.length>0&&<div className="border-t border-ink/10 bg-cream/70 p-6"><div className="mb-4 flex items-center justify-between"><span className="text-sm text-ink-soft">Total</span><span className="font-tag text-xl font-bold text-ink">{formatCurrency(total)}</span></div><Link href="/checkout" onClick={onClose} className="flex w-full items-center justify-center gap-2 rounded-xl bg-poppy py-4 text-sm font-bold text-white hover:bg-poppy-dark">Proceed to checkout<ArrowRight className="h-4 w-4"/></Link><p className="mt-3 text-center text-[11px] text-ink-soft">You&apos;ll choose your saved delivery address at checkout.</p></div>}</aside></>;
}
